<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'setasign\\Fpdi\\' => array($vendorDir . '/setasign/fpdi/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Laminas\\Escaper\\' => array($vendorDir . '/laminas/laminas-escaper/src'),
    'Config\\' => array($baseDir . '/app/Config'),
    'CodeIgniter\\' => array($vendorDir . '/codeigniter4/framework/system'),
    'App\\' => array($baseDir . '/app'),
);
