<?php return array(
    'root' => array(
        'name' => 'codeigniter4/appstarter',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '30609d6f9596e92e518844b47dbf8c0fd14a7ac1',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'codeigniter4/appstarter' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '30609d6f9596e92e518844b47dbf8c0fd14a7ac1',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeigniter4/framework' => array(
            'pretty_version' => 'v4.6.4',
            'version' => '4.6.4.0',
            'reference' => 'e4d3702037a34549582453dbf59b7b67877ae82e',
            'type' => 'project',
            'install_path' => __DIR__ . '/../codeigniter4/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.18.0',
            'version' => '2.18.0.0',
            'reference' => '06f211dfffff18d91844c1f55250d5d13c007e18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdf' => array(
            'pretty_version' => '1.8.6',
            'version' => '1.8.6.0',
            'reference' => '0838e0ee4925716fcbbc50ad9e1799b5edfae0a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.6.4',
            'version' => '2.6.4.0',
            'reference' => '4b53852fde2734ec6a07e458a085db627c60eada',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
